backend/app/accounts/urls.py
from django.urls import path
from .views import user_login, user_logout, redirect_view

app_name = 'accounts'

urlpatterns = [
    path('', redirect_view, name='redirect'),
    path('accounts/login/', user_login, name='login'),
    path('accounts/logout/', user_logout, name='logout')
]

backend/app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('accounts.urls', namespace='accounts')),

    path('department/', include('department.urls', namespace='department')),
    path('patient/analysis/', include('patient_analysis.urls', namespace='analysis')),
    path('patient/initial_examination/', include('patient_initial_examination.urls', namespace='examination')),
    path('patient/diagnoses/', include('patient_diagnoses.urls', namespace='diagnoses')),
    path('patient/diary/', include('patient_diary.urls', namespace='diary')),
    path('patient/', include('patient.urls', namespace='patient')),
]

backend/app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from .managers import DoctorManager
from department.models import Department

class Doctor(AbstractBaseUser, PermissionsMixin): # Таблица врача
    iin = models.CharField(primary_key=True, max_length=12)
    phone_number = models.CharField(max_length=15)
    position = models.CharField(max_length=100)
    password = models.CharField(max_length=128)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    email = models.EmailField(unique=True, null=True, blank=True)
    USERNAME_FIELD = 'iin'
    REQUIRED_FIELDS = ['phone_number', 'password', 'first_name', 'last_name', 'surname', 'position']
    is_staff = models.BooleanField(default=False)  # Добавление атрибута is_staff
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    objects = DoctorManager()

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.surname}"

backend/app/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from app import settings
from department.services import get_first_department
from django.views.decorators.csrf import csrf_exempt

def redirect_view(request):
    if not request.user.is_authenticated:
        print('пользователь не авторизован')
        return redirect(settings.LOGIN_URL)
    else:
        print('пользователь авторизован')
        first_department = get_first_department()
        if first_department:
            return redirect('department:department', department_id='all')
        else:
         # Что то нужно показать если отделение нет
            return None
            
@csrf_exempt
def user_login(request):
    if request.method == 'POST':
        phone_number = request.POST['phone']
        iin = request.POST['iin']
        code = request.POST['code']
        user = authenticate(request, username=iin, password=code, phone_number=phone_number)
        print(user)
        if user is not None:
            login(request, user)  # Аутентификация пользователя
            print("процесс аутентефикации", user.is_authenticated)
            return redirect('department:department', department_id='all')
        else:
            return render(request, 'accounts/login.html', {'error_message': 'Неверные учетные данные'})
    else:
        return render(request, 'accounts/login.html')
    

def user_logout(request):
    logout(request)
    return redirect('/accounts/login')

backend/app/accounts/templates/accounts/Auto.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Аутентификация</title>
    <link rel="stylesheet" href="Auntf.css">
</head>
<body>
    <div class="loginForm">
        <h2>Вход в систему</h2>
        <form id="myForm" method="post" action="{% url 'my_view' %}">
            {% csrf_token %}
            <div id="step1">
                <label for="phone_number">Номер телефона:</label>
                <input type="text" id="phone_number" name="phone_number" placeholder="Введите номер телефона" pattern="\d{11}" required>
                <br>
                <label for="iin">ИИН:</label>
                <input type="text" id="iin" name="iin" placeholder="Введите ИИН" pattern="\d{12}" required>
                <br>
                <button type="submit">Отправить</button>
            </div>
      
            <div id="step2" style="display:none;">
                <label for="code">Введите 4-значный код</label>
                <input type="text" id="code" name="code" pattern="\d{4}" required>
                <button type="submit">Подтвердить</button>
            </div>
            
        </form>
    </div>
    <script src="script.js"></script>
</body>
</html>

backend/app/accounts/templates/accounts/login.html
{%load static%}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Аутентификация</title>
    <link rel="stylesheet" href="{% static 'css/auth.css' %}">
</head>
<body>
    <div class="loginForm">
        <h2>Вход в систему МИС Надежда</h2>
        <form id="myForm" method="post" action="{% url 'accounts:login' %}">
            {%csrf_token%}
            <div id="step1">
                <label for="phone_number">Номер телефона:</label>
                <input name="phone" type="text" id="phone_number" placeholder="Введите номер телефона" pattern="\d{11}" required>
                <br>
                <label for="iin">ИИН:</label>
                <input name="iin" type="text" id="iin" placeholder="Введите ИИН" pattern="\d{12}" required>
                <br>
                <button type="button" onclick="showCodeStep()">Отправить</button>
            </div>
      
            <div id="step2" style="display:none;">
                <label for="code">Введите 4-значный код</label>
                <input name="code" type="text" id="code" pattern="\d{4}" required>
                <button type="submit">Подтвердить</button>
            </div>
            
        </form>
        <span>{{ error_message }}</span>
    </div>
    <script src="{%static 'scripts/auth.js'%}"></script>
</body>
</html>