backend/app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('accounts.urls', namespace='accounts')),

    path('department/', include('department.urls', namespace='department')),
    path('patient/analysis/', include('patient_analysis.urls', namespace='analysis')),
    path('patient/initial_examination/', include('patient_initial_examination.urls', namespace='examination')),
    path('patient/diagnoses/', include('patient_diagnoses.urls', namespace='diagnoses')),
    path('patient/diary/', include('patient_diary.urls', namespace='diary')),
    path('patient/', include('patient.urls', namespace='patient')),
]

backend/app/patient_diagnoses/urls.py
from django.urls import path
from .views import diagnosis_view, patient_diagnoses_view


app_name = 'diagnoses'

urlpatterns = [
    path('<int:diagnosis_id>',diagnosis_view, name='diagnosis'),
    path('list/<int:medcard_id>',patient_diagnoses_view, name='patient_diagnoses')

]

backend/app/patient_initial_examination/urls.py
from django.urls import path
from .views import examination_view

app_name = 'examination'

urlpatterns = [
    path('<int:examination_id>', examination_view, name='index')
]

backend/app/patient_initial_examination/models.py
from django.db import models
from django.utils import timezone
from patient.models import Patient, MedCard
from accounts.models import Doctor
# Create your models here.
class InitialExamination(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    author = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)
    med_card = models.ForeignKey(MedCard, on_delete=models.CASCADE)
    bypass = models.CharField(max_length=500, null=True, blank=True) # Состав осмотра
    complaints = models.CharField(max_length=500, null=True, blank=True) # Жалобы больного
    medical_history = models.CharField(max_length=500, null=True, blank=True) # Анамнез заболевания
    anamnesis_of_life = models.CharField(max_length=500, null=True, blank=True) # Анамнез жизни
    allergic_history = models.CharField(max_length=500, null=True, blank=True) # Аллергический анамнез
    transfusion_history = models.CharField(max_length=500, null=True, blank=True) # Трансфизионный анамнез
    objective_examination_data = models.CharField(max_length=500, null=True, blank=True) # Данные объективного осмотра
    bolean_choices = [(True, 'Да'), (False, 'Нет')]
    is_examined_on_an_outpatient_basis = models.BooleanField(choices=bolean_choices, default=False) # Исследовался ли амбулаторно
    examination_plan = models.CharField(max_length=500, null=True, blank=True) # План обследования
    treatment_plan = models.CharField(max_length=500, null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return f"Первичный осмотр {self.patient}"

backend/app/patient_initial_examination/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from app import settings
from .examination_services import *
from patient.services import get_patient_by_medcard

# Create your views here.
def examination_view(request, examination_id):
    if not request.user.is_authenticated:
        print('пользователь не авторизован')
        return redirect(settings.LOGIN_URL)
    examination = get_examination(examination_id)
    medcard = examination.med_card.id
    patient = get_patient_by_medcard(medcard)
    context = {
        'examination':examination,
        'patient':patient,
        }
    
    return render(request, 'initial_examination/initial_examination.html', context)

backend/app/patient_initial_examination/templates/initial_examination/initial_examination.html
{%extends 'department/base.html'%}
{%load static%}
{% load custom_tags %}
{%block style%}
<link href="/img/app-icon-all.png" rel="shortcut icon">
<link rel="stylesheet" href={% static "css/inspections.css"%}>
{%endblock%}
{%block content%}
<a href="javascript:history.back()" style="color: #000000; font-size: 20px;"><i class="fa-solid fa-arrow-right-from-bracket"id="exit" style="transform:rotate(180deg); margin-right: 20px;font-size: 24px; color:  #000000;margin-top: 20px;margin-left: 20px;"></i>Назад</a>
    <div id="popup1" class="popup">
        <h2>Осмотр от {{examination.date|date:"d.m.Y H:i"}}</h2>
        <div class="span-column">
            <span class="item-title">Пациент</span>
            <span class="item-date">{{patient.last_name}} {{patient.first_name}} {{patient.surname}}, {{patient.age}} {{patient.age|age_pluralize}}</span>
            <a href="{% url 'diagnoses:patient_diagnoses' examination.med_card.id%}">Диагнозы</a>
            <span class="item-title">Состав осмотра</span>
            <span class="item-date">{{examination.bypass}}</span>
            <span class="item-title">Автор</span>
            <span class="item-date">{{examination.author}}</span>
            <span class="item-title">Анамнез заболевания</span>
            <span class="item-date">{{examination.medical_history}}</span>
            <span class="item-title">Анамнез жизни</span>
            <span class="item-date">{{examination.anamnesis_of_life}}</span>
            <span class="item-title">Аллергологический анамнез</span>
            <span class="item-date">{{examination.allergic_history}}</span>
            <span class="item-title">Трансфузионный анамнез</span>
            <span class="item-date">{{examination.transfusion_history}}</span>
            <span class="item-title">Данные объективного осмотра</span>
            <span class="item-date">{{examination.objective_examination_data}}</span>
            <span class="item-title">Обследован(а) амбулаторно</span>
            <span class="item-date">{{examination.get_is_examined_on_an_outpatient_basis_display}}</span>
            <span class="item-title">План обследования</span>
            <span class="item-date">{{examination.examination_plan}}</span>
            <span class="item-title">План лечения</span>
            <span class="item-date">{{examination.treatment_plan}}</span>
        </div>
        <button onclick="Close()">Закрыть</button>
    </div>
    <div class="diagnoses_popup">
</div>
{%endblock%}
{%block scripts%}
<script src="{%static 'scripts/close.js'%}"></script>
{%endblock%}

    