backend/app/accounts/urls.py
from django.urls import path
from .views import user_login, user_logout, redirect_view

app_name = 'accounts'

urlpatterns = [
    path('', redirect_view, name='redirect'),
    path('accounts/login/', user_login, name='login'),
    path('accounts/logout/', user_logout, name='logout')
]

backend/app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('accounts.urls', namespace='accounts')),

    path('department/', include('department.urls', namespace='department')),
    path('patient/analysis/', include('patient_analysis.urls', namespace='analysis')),
    path('patient/initial_examination/', include('patient_initial_examination.urls', namespace='examination')),
    path('patient/diagnoses/', include('patient_diagnoses.urls', namespace='diagnoses')),
    path('patient/diary/', include('patient_diary.urls', namespace='diary')),
    path('patient/', include('patient.urls', namespace='patient')),
]

backend/app/department/urls.py
from django.urls import path
from . import views

app_name = 'department'

urlpatterns = [
    path('<str:department_id>/', views.view_department, name='department'),
    path('<str:department_id>/fetch/', views.fetch_patients, name='fetch_patients'),
    path('<str:department_id>/search_patients', views.search_patients, name='search')
    
]

backend/app/patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('<str:patient_id>', views.main_data_view, name='index'),
    path('<str:patient_id>/sorting', views.sorting, name='sorting'),
    path('<str:patient_id>/update_patient_data', views.update_patient_data, name='update_patient_data'),
    path('<str:patient_id>/add-diary', views.add_diary, name='update_patient_data'),
    path('<str:patient_id>/search_analyses', views.search_analyses, name='search_analyses'),
    path('<str:patient_id>/archive_medcards', views.archive_medcards_list_view, name='archive_medcards'),
    path('<str:patient_id>/archive_medcards/<str:medcard_id>', views.archive_medcard_view, name='archive_medcards'),
    path('<str:patient_id>/hospitalization_info', views.hospitalization_info_view, name='archive_medcards'),
    path('<str:patient_id>/archive_medcards/<str:medcard_id>/hospitalization_info', views.hospitalization_info_view, name='archive_medcards'),

]

backend/app/department/models.py
'''Модель Отделения'''

from django.db import models

# Create your models here.
class Department(models.Model): # Таблица отделения
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)

    def __str__(self) -> str:
        return f"{self.name}"
    

backend/app/department/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import redirect
from django.core import serializers
from django.http import JsonResponse
from django.db.models import Q
import json
from accounts import doctor_services
from django.http import JsonResponse
from app import settings
from .services import *
from django.views.generic.list import ListView
# Create your views here.

def view_department(request, department_id):
    
    if not request.user.is_authenticated:
        print('пользователь не авторизован')
        return redirect(settings.LOGIN_URL)
    departments = get_departments()
    doctor_name = doctor_services.get_doctor_full_name(request.user)

    if department_id == 'all':
        hospitalizations_of_department = get_all_hospitalizations()
        hospitalizations_of_doctor = get_hospitalizations_of_doctor(hospitalizations_of_department, request)
        current_department_id = 'all'
    else:
        hospitalizations_of_department = get_hospitalizations_of_department(department_id)
        hospitalizations_of_doctor = get_hospitalizations_of_doctor(hospitalizations_of_department, request)
        current_department_id = int(department_id)
        print(hospitalizations_of_doctor, "пациенты доктора")
    context = {
        'current_department_id': current_department_id,
        'departments':departments,
        'hospitalizations_of_department': hospitalizations_of_department,
        'title': 'Отделение',
        'doctor_name':doctor_name,
        'hospitalizations_of_doctor':hospitalizations_of_doctor,
    }
    return render(request, 'department/department.html', context)

def fetch_patients(request, department_id):
    if request.is_ajax():
        if department_id == 'all':
            hospitalizations_of_department = get_all_hospitalizations()
            hospitalizations_of_doctor = get_hospitalizations_of_doctor(hospitalizations_of_department, request)
        else:
            hospitalizations_of_department = get_hospitalizations_of_department(department_id)
            hospitalizations_of_doctor = get_hospitalizations_of_doctor(hospitalizations_of_department, request)

        department_patients = []
        doctor_patients = []
        department_patients = get_patients(hospitalizations_of_department)
        doctor_patients = get_patients(hospitalizations_of_doctor)
        reanimations_of_department = get_reanimations(department_patients)
        reanimations_of_doctor = get_reanimations(doctor_patients)
        sent_data = {'patients_of_department': department_patients, 'reanimations_of_department':reanimations_of_department, 'patients_of_doctor': doctor_patients, 'reanimations_of_doctor': reanimations_of_doctor}
        return JsonResponse(sent_data)
    
def search_patients(request, department_id): 
    if request.is_ajax():
        query = request.GET.get('q')
        if department_id == 'all':
            hospitalizations_of_department = get_all_hospitalizations()
            hospitalizations_of_doctor = get_hospitalizations_of_doctor(hospitalizations_of_department, request) 
        else:      
            hospitalizations_of_department = get_hospitalizations_of_department(department_id)
            hospitalizations_of_doctor = get_hospitalizations_of_doctor(hospitalizations_of_department, request)
        hospitalizations_of_department = hospitalizations_of_department.filter(
            Q(patient_id__first_name__iregex=query) | Q(patient_id__last_name__iregex=query) | Q(patient_id__surname__iregex=query)
        )
        hospitalizations_of_doctor = hospitalizations_of_doctor.filter(
            Q(patient_id__first_name__iregex=query) | Q(patient_id__last_name__iregex=query) | Q(patient_id__surname__iregex=query)
        )
        
        department_patients = []
        doctor_patients = []
        department_patients = get_patients(hospitalizations_of_department)
        doctor_patients = get_patients(hospitalizations_of_doctor)      
        reanimations_of_department = get_reanimations(department_patients)
        reanimations_of_doctor = get_reanimations(doctor_patients)
        sent_data = {'patients_of_department': department_patients, 'reanimations_of_department':reanimations_of_department, 'patients_of_doctor': doctor_patients, 'reanimations_of_doctor': reanimations_of_doctor}
        return JsonResponse(sent_data)
    

backend/app/department/templates/department/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <title>{{title}}</title>
    {%block style%}
    {%endblock%}
</head>
<body>
    {%block header%}
    {%endblock%}
    <main>
        {%block content%}
        {%endblock%}
    </main>
</body>
{%block scripts%}
{%endblock%}
<script src="https://kit.fontawesome.com/09ef455c42.js" crossorigin="anonymous"></script>
<script src="{%static 'scripts/logout.js'%}"></script>
</html>

backend/app/department/templates/department/department.html
{%extends 'department/base.html'%}
{%load static%}
{% load custom_tags %}
{%block style%}
<link rel="stylesheet" href={%static "css/department.css" %}>
{%endblock%}
{%block header%}
<header>
    <div style="flex-direction: row;width: 100%; max-width: 100%; display: flex; justify-content: space-between; align-items: center;">
        <img src="{% static "img/head-logo.png" %}" alt="logo" class="logo">
       
        <form>
            <label for="department-select">Ваши отделения</label>
            <select name="department" id="department-select" class="ds-select" onchange="ShowPatients()">
                <option value="all" {% if current_department_id == 'all' %}selected{% endif %}>Все отделения</option>
                {% for dep in departments %}
                <option value="{{ dep.id }}" {% if dep.id == current_department_id %}selected{% endif %}>{{ dep }}</option>
                {% endfor %}
            </select>
        </form>
        
        
        <div style="position: relative; display: inline-block;">
            <a href="#" class="dropdown-toggle"><i class="fa-solid fa-user-nurse doctor doctor-icon"></i><span>{{doctor_name}}</span></a>
            <div class="dropdown-menu">
                <div class="doctor-name">{{doctor_name}}</div>
                <button href="{% url 'accounts:logout' %}  "class="logout-button" onclick="Exit()" >Выход</button>
            </div>
        </div>
    </div>
</header>
{%endblock%}
{%block content%}
    <div class="block1">
        <div class="block2">
            <button class="btn_block2 active" id="all-patients-btn">Все пациенты</button>
            <button class="btn_block2" id="my-patients-btn">Мои пациенты</button> 
        </div>
        <form class="input-group" onsubmit="return false;">
            <input id="search-input" name="q" type="search" class="search" placeholder="Поиск пациента">
            <button id="search-btn" type="button" onclick="search_patients()" class="search-btn">Поиск</button>
        </form>
    </div>
    <div class="patient-list">
        {%for hospitalization in hospitalizations_of_department%}
            <a id="{{hospitalization.id}}" data-reanimation='{{hospitalization.reanimation}}' class="patient-item" href="{% url 'patient:index' hospitalization.patient_id.id%}" style="text-decoration: none; color: black;">
                <span><i style="margin-right: 5px;" class="fa-solid fa-clipboard-user"></i> {{hospitalization.patient_id.last_name}} {{hospitalization.patient_id.first_name}} {{hospitalization.patient_id.surname}}</span>
                <span id="shadow">{{ hospitalization.patient_id.age }} {{ hospitalization.patient_id.age|age_pluralize }}, госпитализация: {{hospitalization.receipt_date|date:"d.m.Y H:i"}}</span>
            </a> 
        {%endfor%}
        </div>

    <div class="my-patients">
        {%for hospitalization in hospitalizations_of_doctor%}
            <a class="patient-item" data-reanimation='{{hospitalization.reanimation}}' href="{% url 'patient:index' hospitalization.patient_id.id%}" style="text-decoration: none; color: black;">
                <span><i style="margin-right: 10px;" class="fa-solid fa-clipboard-user"></i>{{hospitalization.patient_id.last_name}} {{hospitalization.patient_id.first_name}} {{hospitalization.patient_id.surname}}</span>
                <span  id="shadow">{{ hospitalization.patient_id.age }} {{ hospitalization.patient_id.age|age_pluralize }}, госпитализация: {{hospitalization.receipt_date|date:"d.m.Y H:i"}}</span>
            </a> 
        {%endfor%}
    </div>
{%endblock%}

{%block scripts%}
<script src="{%static "scripts/department.js"%}"></script>
<script src = "{%static "scripts/get_patients.js"%}"></script>
{%endblock%}