backend/app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('accounts.urls', namespace='accounts')),

    path('department/', include('department.urls', namespace='department')),
    path('patient/analysis/', include('patient_analysis.urls', namespace='analysis')),
    path('patient/initial_examination/', include('patient_initial_examination.urls', namespace='examination')),
    path('patient/diagnoses/', include('patient_diagnoses.urls', namespace='diagnoses')),
    path('patient/diary/', include('patient_diary.urls', namespace='diary')),
    path('patient/', include('patient.urls', namespace='patient')),
]

backend/app/patient_diagnoses/urls.py
from django.urls import path
from .views import diagnosis_view, patient_diagnoses_view


app_name = 'diagnoses'

urlpatterns = [
    path('<int:diagnosis_id>',diagnosis_view, name='diagnosis'),
    path('list/<int:medcard_id>',patient_diagnoses_view, name='patient_diagnoses')

]

backend/app/patient_diagnoses/models.py
from django.db import models
from patient.models import Patient, MedCard
from accounts.models import Doctor
from django.utils import timezone
# Create your models here.

class DiagnosesName(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=7)
    def __str__(self):
        return f'({self.code}) {self.name}'

class Diagnoses(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    author = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True )
    med_card = models.ForeignKey(MedCard, on_delete=models.CASCADE, null=True)
    code = models.ForeignKey(DiagnosesName, on_delete=models.CASCADE)
    kind_choices = [('pr', 'Предварительный'), ('cl', 'Клинический'), ('fi', 'Окончательный'), ('pa', 'Патологоанатомический'), ('st', 'Этапный')] # Патологоанатомический, этапный
    kind = models.CharField(max_length=2, choices=kind_choices, null=True, blank=True)
    type_choices = [('main', 'Основное'), ('сopg', 'Конкурирующее'), ('back', 'Фоновое'), ('copn', 'Осложнение')]
    type = models.CharField(max_length=4, choices=type_choices, null=True, blank=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return f'{self.code}'

backend/app/patient_diagnoses/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from patient.services import get_patient_by_medcard
from .diagnoses_services import *
from accounts.doctor_services import get_doctor_full_name
from app import settings

# Create your views here.

def diagnosis_view(request, diagnosis_id):
    if not request.user.is_authenticated:
        print('пользователь не авторизован')
        return redirect(settings.LOGIN_URL)
    diagnosis = get_diagnosis(diagnosis_id)
    medcard = diagnosis.med_card.id
    patient = get_patient_by_medcard(medcard)
    
    context = {
        'diagnosis':diagnosis,
        'patient':patient,
        }
    
    return render(request, 'diagnoses/diagnosis.html', context)

def patient_diagnoses_view(request, medcard_id):
    diagnoses = get_diagnoses(medcard_id)
    patient = get_patient_by_medcard(medcard_id)
    context = {
        'diagnoses': diagnoses,
        'patient':patient
    }
    return render(request, 'diagnoses/patient_diagnoses.html', context)

backend/app/patient_diagnoses/templates/diagnoses/diagnosis.html
{%extends 'department/base.html'%}
{%load static%}
{% load custom_tags %}
{%block style%}
<link href={% static "img/app-icon-all.png"%} rel="shortcut icon">
<link rel="stylesheet" href={% static "css/diagnoses.css"%}>
{%endblock%}
{%block content%}
<a href="javascript:history.back()" style="color: #000000; font-size: 20px;"><i class="fa-solid fa-arrow-right-from-bracket"id="exit" style="transform:rotate(180deg); margin-right: 20px;font-size: 24px; color:  #000000;margin-top: 20px;margin-left: 20px;"></i>Назад</a>
    <div id="popup1" class="popup">
        <h2>Диагноз от {{diagnosis.date|date:"d.m.Y H:i"}}</h2>
        <div class="span-column">
          <span class="item-title">Пациент</span>
          <span class="item-date">{{patient.last_name}} {{patient.first_name}} {{patient.surname}} {{patient.age}} {{patient.age|age_pluralize}}</span>
          <span class="item-title">Автор</span>
          <span class="item-date">{{diagnosis.author}}</span>
          <span class="item-title">Код</span>
          <span class="item-date">{{diagnosis.code}}</span>
          <span class="item-title">Вид</span>
          <span class="item-date">{{diagnosis.get_kind_display}}</span>
          <span class="item-title">Тип</span>
          <span class="item-date">{{diagnosis.get_type_display}}</span>
          <span class="item-title">Описание</span>
          <span class="item-date">{{diagnosis.description}}</span>
        </div>
        <button onclick="Close()">Закрыть</button>
    </div>
{%endblock%}
{%block scripts%}
<script src="{%static 'scripts/close.js'%}"></script>
{%endblock%}

backend/app/patient_diagnoses/templates/diagnoses/patient_diagnoses.html
{%extends 'department/base.html'%}
{%load static%}
{% load custom_tags %}
{%block style%}
<link href={% static "img/app-icon-all.png"%} rel="shortcut icon">
  <link rel="stylesheet" href={% static "css/diagnoses_osmoter.css"%}>
{%endblock%}
{%block content%}

    <a href="javascript:history.back()" style="color: #000000; font-size: 20px;"><i class="fa-solid fa-arrow-right-from-bracket"id="exit" style="transform:rotate(180deg); margin-right: 20px;font-size: 24px; color:  #000000;margin-top: 20px;margin-left: 20px;"></i>Назад</a>
    <div id="popup1" class="popup">
      <h2>Диагнозы</h2>
      <div id="content12" class="content12">
        <div class="buttons-vertical">
          {%for diagnosis in diagnoses%}
          <div class="dropdown-item" onclick="diagnoses('{{diagnosis.id}}')" id="d1">
            <div class="span-column1">
                <span class="item-title">{{diagnosis.code}}</span>
                <span class="item-date">{{diagnosis.date|date:"d.m.Y H:i"}}</span>
                <span class="item-date">{{diagnosis.get_kind_display}}</span>
            </div>
            <i class="fa-solid fa-arrow-right awesome"></i>
          </div>
        </div>
        {%endfor%}
      </div>
      <button onclick="Close()">Закрыть</button>
    </div>
{%endblock%}
{%block scripts%}
<script src="{% static 'scripts/diagnoses.js'%}"></script>
<script src="{%static 'scripts/close.js'%}"></script>
<script src="https://kit.fontawesome.com/09ef455c42.js" crossorigin="anonymous"></script>
{%endblock%}
  